name: Visitor Count

on:
  push:
    branches:
      - main

jobs:
  update-visitor-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Increment visitor count
        run: |
          if [ ! -f visitor-count.txt ]; then
            echo "0" > visitor-count.txt
          fi
          visitor_count=$(cat visitor-count.txt)
          visitor_count=$((visitor_count + 1))
          echo $visitor_count > visitor-count.txt
      - name: Commit changes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Git config
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: Commit and push
        run: |
          git add visitor-count.txt
          git commit -m 'Update visitor count'
          git push
